# Generated by Django 6.0 on 2026-01-06 23:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Artist biography')),
                ('image', models.ImageField(blank=True, help_text='Artist profile picture', null=True, upload_to='artists/')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='music_artis_name_e97718_idx')],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(blank=True, help_text='Album cover art', null=True, upload_to='album_covers/')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('record_label', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music.artist')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ['-release_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(help_text='Supported formats: MP3, WAV, OGG, M4A, FLAC', upload_to='music_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a', 'flac'])])),
                ('duration', models.DurationField(blank=True, help_text='Song duration (HH:MM:SS)', null=True)),
                ('lyrics', models.TextField(blank=True, help_text='Song lyrics')),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('play_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=True, help_text='Make this song visible to all users')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this song on homepage')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='music.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.artist')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='music.genre')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from 1 to 5 stars')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='music.song')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Custom playlist cover image', null=True, upload_to='playlist_covers/')),
                ('is_public', models.BooleanField(default=False, help_text='Make this playlist visible to all users')),
                ('is_collaborative', models.BooleanField(default=False, help_text='Allow other users to add songs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
                ('songs', models.ManyToManyField(blank=True, related_name='in_playlists', to='music.song')),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('play_duration', models.DurationField(blank=True, help_text='How long the song was played', null=True)),
                ('completed', models.BooleanField(default=False, help_text='Was the song played completely')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to='music.song')),
            ],
            options={
                'verbose_name': 'Play History',
                'verbose_name_plural': 'Play Histories',
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='music.song')),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music.song')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['title'], name='music_album_title_ddf06b_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['artist', 'release_date'], name='music_album_artist__e74ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['title'], name='music_song_title_8e56ff_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['artist'], name='music_song_artist__c5a493_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['genre'], name='music_song_genre_i_6ec8e3_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['-play_count'], name='music_song_play_co_4fba2a_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['-upload_date'], name='music_song_upload__14d0f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'song')},
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['user', '-created_at'], name='music_playl_user_id_0f2ee4_idx'),
        ),
        migrations.AddIndex(
            model_name='playhistory',
            index=models.Index(fields=['user', '-played_at'], name='music_playh_user_id_5396b0_idx'),
        ),
        migrations.AddIndex(
            model_name='playhistory',
            index=models.Index(fields=['song', '-played_at'], name='music_playh_song_id_a0c6d0_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', '-added_at'], name='music_favor_user_id_5193a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'song')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['song', '-created_at'], name='music_comme_song_id_161c28_idx'),
        ),
    ]
